import React, { Component, Fragment } from 'react';
import { withStyles, withTheme } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';
import SvgIcon from '@material-ui/core/SvgIcon';
import PropTypes from 'prop-types';

const styles = ({
  svg: {
    color: '#9FC950',
    width: '100%',
    height: '5em',
    padding: '1em',
    overflow: 'visible',
  },
  wrapper: {
    textAlign: 'center',
    padding: '0 3.7142857142857144rem',
    marginBottom: '2.142857142857143rem',
  },
});

class Success extends Component {
  successEnabled = classes => (
    <Fragment>
      <div className={classes.wrapper}>
        <SvgIcon className={classes.svg}>
          {/* eslint-disable-next-line max-len */}
          <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z" />
        </SvgIcon>
        <Typography variant="h5">You&apos;re All Set!</Typography>
        <Typography>You will be required to enter the one time code generated by Google Authenticator the next time you log in.</Typography>
      </div>
    </Fragment>
  );

  successDisabled = classes => (
    <Fragment>
      <div className={classes.wrapper}>
        <SvgIcon className={classes.svg}>
          {/* eslint-disable-next-line max-len */}
          <path d="M15,3C8.373,3,3,8.373,3,15c0,6.627,5.373,12,12,12s12-5.373,12-12C27,8.373,21.627,3,15,3z M21.707,12.707l-7.56,7.56 c-0.188,0.188-0.442,0.293-0.707,0.293s-0.52-0.105-0.707-0.293l-3.453-3.453c-0.391-0.391-0.391-1.023,0-1.414s1.023-0.391,1.414,0 l2.746,2.746l6.853-6.853c0.391-0.391,1.023-0.391,1.414,0S22.098,12.316,21.707,12.707z" />
        </SvgIcon>
        <Typography variant="h5">You&apos;re All Set!</Typography>
        <Typography>2FA has been disabled on your account. You will no longer be required to enter Google Authenticator code upon login.</Typography>
      </div>
    </Fragment>
  );

  render() {
    const { enabled, classes } = this.props;

    return enabled ? this.successEnabled(classes) : this.successDisabled(classes);
  }
}

Success.propTypes = {
  enabled: PropTypes.bool.isRequired,
  classes: PropTypes.object.isRequired
};

export default withTheme()(withStyles(styles)(Success));



// WEBPACK FOOTER //
// ./src/components/settings/success.js